[package]
name = "rum"
version = "0.1.0"
edition = "2021"
authors = ["Nicholas Mendes <nicholas_mendes@uri.edu>", "Matthew Kelley <matthew_kelley@uri.edu>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
